//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinMute.rc
//
#define IDI_APP                         5
#define IDD_ABOUT                       9
#define IDS_LANG_NAME                   101
#define IDS_MAIN_ERROR_SETTINGS_INIT_TITLE 102
#define IDS_MAIN_ERROR_SETTINGS_INIT_TEXT 103
#define IDI_TRAY_BRIGHT                 104
#define IDS_MAIN_ERROR_WINMUTE_ALREADY_RUNNING_TITLE 104
#define IDI_TRAY_DARK                   105
#define IDS_MAIN_ERROR_WINMUTE_ALREADY_RUNNING_TEXT 105
#define IDR_TRAYMENU                    106
#define IDS_MAIN_ERROR_INIT_WINMUTE_TITLE 106
#define IDS_MAIN_ERROR_INIT_WINMUTE_TEXT 107
#define IDD_SETTINGS                    109
#define IDD_SETTINGS_GENERAL            114
#define IDD_SETTINGS_QUIETHOURS         116
#define IDD_ABOUT_LICENSE               118
#define IDD_ABOUT_WINMUTE               120
#define IDI_ICON1                       122
#define IDI_SETTINGS                    122
#define IDD_SETTINGS_MUTE               123
#define IDD_SETTINGS_WIFI               127
#define IDD_SETTINGS_WIFI_ADD           129
#define IDD_SETTINGS_BLUETOOTH          131
#define IDD_DIALOG1                     133
#define IDD_SETTINGS_BLUETOOTH_ADD      133
#define IDD_MANAGE_ENDPOINTS            135
#define IDD_DIALOG2                     137
#define IDD_MANAGE_ENDPOINTS_ADD        137
#define IDC_LINK_HOMEPAGE               1001
#define IDC_LINK_SUPPORT                1002
#define IDC_LINK_PROJECT                1002
#define IDC_ENABLEQUIETHOURS            1003
#define IDC_LINK_TICKETS                1003
#define IDC_QUIETHOURS_START            1004
#define IDC_QUIETHOURS_END              1005
#define IDC_FORCEUNMUTE                 1006
#define IDC_SHOWNOTIFICATIONS           1007
#define IDC_TREE1                       1008
#define IDC_MANAGE_AUDIO_ENDPOINTS_INDIVIDUALLY 1008
#define IDC_TAB1                        1010
#define IDC_SETTINGS_TAB                1010
#define IDC_CHECK1                      1011
#define IDC_RUNONSTARTUP                1011
#define IDC_MUTE_WHEN_WS_LOCKED         1011
#define IDC_ENABLE_WIFI_MUTE            1011
#define IDC_ENABLELOGGING               1012
#define IDC_CHECK3                      1013
#define IDC_OPENLOG                     1014
#define IDC_LICENSETEXT                 1015
#define IDC_ABOUT_TAB                   1016
#define IDC_ABOUTTEXT                   1019
#define IDC_TITLE                       1020
#define IDC_ABOUT_TITLE                 1020
#define IDC_MUTE_WHEN_SCREENSAVER_STARTS 1021
#define IDC_MUTE_WHEN_SCREEN_OFF        1022
#define IDC_MUTE_WHEN_RDP_SESSION       1023
#define IDC_WIFI_LIST                   1023
#define IDC_RESTOREVOLUME               1024
#define IDC_WIFI_ADD                    1024
#define IDC_MUTE_WHEN_SHUTDOWN          1025
#define IDC_WIFI_REMOVE                 1025
#define IDC_WIFI_NAME                   1025
#define IDC_MUTE_WHEN_LOGOUT            1026
#define IDC_WIFI_EDIT                   1026
#define IDC_MUTE_WHEN_SLEEP             1027
#define IDC_WIFI_REMOVE2                1027
#define IDC_WIFI_REMOVEALL              1027
#define IDC_CHECK2                      1028
#define IDC_IS_PERMITLIST               1028
#define IDC_STATIC_WLAN_NOT_AVAILABLE   1029
#define IDC_STATIC_BLUETOOTH_NOT_AVAILABLE 1030
#define IDC_BLUETOOTH_ADD               1031
#define IDC_BLUETOOTH_EDIT              1032
#define IDC_BLUETOOTH_REMOVE            1033
#define IDC_BLUETOOTH_REMOVEALL         1034
#define IDC_BLUETOOTH_LIST              1035
#define IDC_ENABLE_BLUETOOTH_MUTE       1036
#define IDC_ENABLE_BLUETOOTH_MUTE_DEVICE_LIST 1037
#define IDC_BT_DEVICE_NAME              1038
#define IDC_LOGFILEPATH                 1040
#define IDC_BUTTON1                     1041
#define IDC_MANAGE_ENDPOINTS            1041
#define IDC_ENDPOINT_LIST_IS_ALLOWLIST  1042
#define IDC_ENDPOINT_LIST_IS_BLOCKLIST  1043
#define IDC_ENDPOINT_LIST               1044
#define IDC_ENDPOINT_ADD                1045
#define IDC_ENDPOINT_EDIT               1046
#define IDC_ENDPOINT_REMOVE             1047
#define IDC_ENDPOINT_REMOVEALL          1048
#define IDC_ENDPOINT_NAME               1049
#define IDC_MUTEDELAY                   1050
#define IDC_LANGUAGE                    1051
#define ID_TRAYMENU_INFO                40001
#define ID_TRAYMENU_                    40002
#define ID_TRAYMENU_MUTEON              40003
#define ID_TRAYMENU_ID                  40004
#define ID_TRAYMENU_MUTEONSCREENSAVER   40005
#define ID_TRAYMENU_40006               40006
#define ID_TRAYMENU_RESTOREAUDIO        40007
#define ID_TRAYMENU_40008               40008
#define ID_TRAYMENU_CONFIGUREQUIETHOURS 40009
#define ID_TRAYMENU_40010               40010
#define ID_TRAYMENU_MUTEON40011         40011
#define ID_TRAYMENU_AFTERWARDS          40012
#define ID_TRAYMENU_40013               40013
#define ID_TRAYMENU_MUTEONSHUTDOWN      40014
#define ID_TRAYMENU_40015               40015
#define ID_TRAYMENU_MUTEONSUSPEND       40016
#define ID_TRAYMENU_40017               40017
#define ID_TRAYMENU_MUTEONLOGOUT        40018
#define ID_TRAYMENU_40019               40019
#define ID_TRAYMENU_MUTENOW             40020
#define ID_TRAYMENU_40021               40021
#define ID_TRAYMENU_EXIT                40022
#define ID_TRAYMENU_MUTE                40023
#define ID_TRAYMENU_MUTEONLOCK          40024
#define ID_TRAYMENU_SETTINGS            40025
#define ID_TRAYMENU_SCREENTURNSOFF      40026
#define ID_TRAYMENU_SCREENSUSPEND       40027
#define ID_TRAYMENU_40028               40028
#define ID_TRAYMENU_40029               40029
#define ID_TRAYMENU_BLUETOOTH           40030
#define ID_TRAYMENU_MUTEONBLUETOOTH     40031
#define ID_TRAYMENU_MUTEONSCREENSUSPEND 40032
#define ID_TRAYMENU_SPECIAL             40033
#define ID_TRAYMENU_40034               40034
#define ID_TRAYMENU_WIFIMUTING          40035
#define ID_TRAYMENU_MUTEONWIFI          40036

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         40037
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
